---
title: "Untitled"
author: "Marida Ianni-Ravn"
date: "2023-01-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#` Wright formula for distribution of freq of susceptibility alleles
#` @param bs Mutation rate to disease class
#` @param bs Mutation rate from disease class
#` @param sigma Scaled strength of selection
#` @param p Frequency of disease mutations
fp <- function(bs,bn,sigma,p){ 
  p^(bs-1)*(1-p)^(bn-1)*exp(sigma*(1-p))
}

findk <- function(bs,bn,sigma){
  # find integrating constant for above
}

# need to find integrating constant
```

```{r}
#` Ewens sampling formula for number of distinct disease alleles from sample of n
#` @param bs Mutation rate to disease class
#` @param n Number of chromosomes sampled
#` @param p Frequency of disease mutations
ewens <- function(n,bs,p){
  is <- seq(0,n-1)
  vec <- (bs*(1-p))/(bs*(1-p)+is)
  print(vec)
  rs <- sum(vec)
  return(rs)
}

ewens <- Vectorize(ewens)
```



```{r}
ps <- seq(0,1,0.1)
fps <- fp(1,0.1,1,ps)
plot(ps,fps)
```


```{r}
plot(ps,fp(1,0.1,1,ps),type="l")
lines(ps,fp(0.1,0.1,1,ps),col="lightblue")
lines(ps,fp(10,0.1,1,ps),col="lightpink")
```


```{r}
plot(ps*fps,ewens(10,0.1,p=ps*fps)) # negative bc of lack of integrating constant.
```

